#include <string>


class Write {
public:
    Writing(){
        Resources = ";Resource file - Generated by the KoolB compiler\n";
        Library = ";Library functions to import to the KoolB program\n";
        FireUpApp = "\n\n;Initialize everything to prepare the program to run\n";
        MainApp = "\n\n;The main body of the program where the program runs\n";
        FinishUpApp = "\n\n;Prepare the program to exit, then terminate the program\n";
        AppData = "\n\n;Data section of the KoolB programp\n";
    }

    // Formats a string of assembly language code into a line and adds it to
    // the desired section.
    void Line(int Section, string Line);

    void Comment(int Section, string Comment);
    
    // Writes all the sections of the programs to files based on the FileName.
    void File(string FileName);

    // Runs the assembler, resource compiler, and linker.
    // Produces an executable
    void BuildApp(string FileName);

    enum Sections{ToData, ToFireUp, ToMain, ToFinishUp, ToResource, ToLibrary};

private:
    /*
    - AppData - Contains variables and data that the program will need.

    - FireUpApp - Contains initialization routines for the program like object
    constructors and internal code that gets the program ready to run user code.

    - MainApp - Contains the user's code.

    - FinishAppUp - Contains routines to clean up after the user and prepare
    the program to exit. Frees all memory associated with objects, variables,
    and the program in general.

    - Resources - Contains instructions for the resource compiler to tell it
    what files and resources to include and how to include them.

    - Library - Contains all the external functions that the program will
    need. (Windows API or Linux C-Library calls)
    */
    std::string AppData;
    std::string FireUpApp;
    std::string MainApp;
    std::string FinishUpApp;
    std::string Resources;
    std::string Library;  
};